### PR TITLE
Fix wishlist

### LINKED ISSUE #358: Wishlist: multiple errors on failed item entry attempt
If user tries to add an item to the wishlist that is already in their wishlist error "Domeeninimi is already in your wishlist" error is returned. But sometimes there are more than one such messages returned

image

if user goes straight to wishlist view after login only one error message is returned, but if he/she has clicked around between different views the number of error messages is raised.

### PR DESCRIPTION
**Pull request by artur-beljajev**
Fixes #358

### CODE REVIEW

File: app/javascript/packs/wishlist_items.js [hunk 1]
```diff
@@ -16,7 +16,15 @@ function onlyUnique(value, index, self) {
...
 }
 
-document.addEventListener('ajax:error', (event) => {
+function clearErrors() {
+    const container = document.getElementById('errors-list');
+
+    while (container.firstChild) {
+        container.removeChild(container.firstChild);
+    }
+}
```
Comment (karlerikounapuu) [inline app/javascript/packs/wishlist_items.js]: As event listener is properly mounted now, why is this part needed though? Only reason I can think of is for a better clarity, since duplicate errors have already vanished.

File: app/javascript/packs/wishlist_items.js [hunk 2]
```diff
@@ -16,7 +16,15 @@ function onlyUnique(value, index, self) {
...
+
+document.body.addEventListener('ajax:error', (event) => {
```
[the remark this answers is not in the document]
Comment (artur-beljajev) [reply app/javascript/packs/wishlist_items.js]: Great. Let @vohmar test it, and see if everything is fine. It's also interesting, how it works if some another JS request is made, since `ajax:xx` callbacks are triggered for any request, not only for POSTing new wishlist item.

File: app/javascript/packs/wishlist_items.js (hunk 1 above)
Comment (artur-beljajev) [reply app/javascript/packs/wishlist_items.js]: I also wanted to get rid of it at first, until I realized that without it every form submit will lead to new errors inserted. So unless they are cleared, they will get appended on and on.
